services:
  keycloak-db:
    ports:
      - "${DB_PORT:-5432}:5432"

  keycloak:
    command: ${KC_COMMAND:-start --import-realm}
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
      KC_HTTP_ENABLED: "true"
      KC_SPI_THEME_STATIC_MAX_AGE: "-1"
      KC_SPI_THEME_CACHE_THEMES: "false"
      KC_SPI_THEME_CACHE_TEMPLATES: "false"
    ports:
      - "${KC_PORT:-8080}:8080"
